# Cargo configuration for Runetika - OPTIMIZED FOR SPEED

[build]
jobs = 4  # Use 4 parallel jobs
# Note: sccache and incremental compilation don't work together
# rustc-wrapper = "/opt/homebrew/bin/sccache"

[env]
CARGO_INCREMENTAL = "1"
# RUSTC_WRAPPER = "/opt/homebrew/bin/sccache"  # Disabled - conflicts with incremental
SCCACHE_CACHE_SIZE = "10G"

# Fast linker settings for macOS
[target.aarch64-apple-darwin]
linker = "clang"
rustflags = [
    "-C", "split-debuginfo=unpacked",
    "-C", "debuginfo=0",  # No debug info for faster builds
    "-C", "target-cpu=native",
]

[target.x86_64-apple-darwin]
linker = "clang"
rustflags = [
    "-C", "link-arg=-fuse-ld=lld",
    "-C", "split-debuginfo=unpacked",
    "-C", "debuginfo=0",
]

# Cargo aliases
[alias]
fast = "build --profile fast"
quick = "run --profile fast"
lint = "clippy -- -D warnings"

[registries.crates-io]
protocol = "sparse"

[net]
retry = 3
git-fetch-with-cli = true  # Faster git operations